# not for production usage
# nodejs webapp
version: '3.9'

services:
  app:
    container_name: wallet_api
  
    image: admiral/admiral_npm:latest   

    env_file:
       - .env
    
    environment: 
      DB_URL: mysql
      
    volumes:
      - ./src:/src
      - ./nodemodules:/src/node_modules    

    ports: 
      - ${WALLET_API_PORT}:${WALLET_API_PORT}

    depends_on: 
      - mysql
    networks:
      - backend

networks:
  backend:
    name: backend_network

