version: '3.9'

services:

  wallet_api-liquibase:

    container_name: wallet_api_liquibase
    image: liquibase/liquibase-mysql  #this is a local

    volumes:
      - ./liquibase/changelog.xml:/liquibase/changelog.xml
      - ./liquibase/scripts:/liquibase/scripts
    
    # todo, load these in
    command: --url=jdbc:mysql://mysql:3306/wallet --username=wallet_user --password=wallet_password --changeLogFile=changelog.xml update    

    networks:
      - backend

networks:
  backend:
    name: backend_network